/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyFeedbacksRouteImport } from './routes/my-feedbacks'
import { Route as SubmitFeedbackRouteImport } from './routes/submit-feedback'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as AdminAllFeedbacksRouteImport } from './routes/admin.all-feedbacks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFeedbacksRoute = MyFeedbacksRouteImport.update({
  id: '/my-feedbacks',
  path: '/my-feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitFeedbackRoute = SubmitFeedbackRouteImport.update({
  id: '/submit-feedback',
  path: '/submit-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAllFeedbacksRoute = AdminAllFeedbacksRouteImport.update({
  id: '/all-feedbacks',
  path: '/all-feedbacks',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/my-feedbacks': typeof MyFeedbacksRoute
  '/submit-feedback': typeof SubmitFeedbackRoute
  '/success': typeof SuccessRoute
  '/admin/all-feedbacks': typeof AdminAllFeedbacksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/my-feedbacks': typeof MyFeedbacksRoute
  '/submit-feedback': typeof SubmitFeedbackRoute
  '/success': typeof SuccessRoute
  '/admin/all-feedbacks': typeof AdminAllFeedbacksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/my-feedbacks': typeof MyFeedbacksRoute
  '/submit-feedback': typeof SubmitFeedbackRoute
  '/success': typeof SuccessRoute
  '/admin/all-feedbacks': typeof AdminAllFeedbacksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/my-feedbacks'
    | '/submit-feedback'
    | '/success'
    | '/admin/all-feedbacks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/my-feedbacks'
    | '/submit-feedback'
    | '/success'
    | '/admin/all-feedbacks'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/my-feedbacks'
    | '/submit-feedback'
    | '/success'
    | '/admin/all-feedbacks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyFeedbacksRoute: typeof MyFeedbacksRoute
  SubmitFeedbackRoute: typeof SubmitFeedbackRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-feedbacks': {
      id: '/my-feedbacks'
      path: '/my-feedbacks'
      fullPath: '/my-feedbacks'
      preLoaderRoute: typeof MyFeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-feedback': {
      id: '/submit-feedback'
      path: '/submit-feedback'
      fullPath: '/submit-feedback'
      preLoaderRoute: typeof SubmitFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/all-feedbacks': {
      id: '/admin/all-feedbacks'
      path: '/all-feedbacks'
      fullPath: '/admin/all-feedbacks'
      preLoaderRoute: typeof AdminAllFeedbacksRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAllFeedbacksRoute: typeof AdminAllFeedbacksRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAllFeedbacksRoute: AdminAllFeedbacksRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MyFeedbacksRoute: MyFeedbacksRoute,
  SubmitFeedbackRoute: SubmitFeedbackRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
